In [1]:
import pandas as pd
import joblib

In [11]:
def save_submission(n_submissions, rf_pred):
    import csv
    n_submissions = int(input("Ingrese el número de submission: "))
    with open(f'./Submissions/submission{n_submissions}_M.csv', 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(['Id', 'Predicted'])
        for i, (x, y) in enumerate(rf_pred):
            writer.writerow([i, f"{x}|{y}"])

In [2]:
sub_id4=joblib.load(r'C:\UdeA\Lab\Final project\Submissions\sub_id4')
sub_id4

array([[478.7 , 327.95],
       [551.35, 578.8 ],
       [208.65, 394.4 ],
       ...,
       [457.45, 588.6 ],
       [229.45, 381.35],
       [408.7 , 211.9 ]])

In [3]:
sub_out=joblib.load(r'C:\UdeA\Lab\Final project\Submissions\sub_out')
sub_out

array([[479.95, 328.1 ],
       [549.55, 577.5 ],
       [208.05, 394.25],
       ...,
       [457.3 , 590.1 ],
       [230.9 , 380.75],
       [407.4 , 212.3 ]])

In [4]:
sub_rnn=joblib.load(r'C:\UdeA\Lab\Final project\Submissions\sub_rnn')
sub_rnn

array([[475.62155, 338.64493],
       [530.90234, 576.9009 ],
       [210.74297, 395.9947 ],
       ...,
       [464.01505, 591.5582 ],
       [237.47446, 381.96082],
       [410.34888, 220.0901 ]], dtype=float32)

In [14]:
import csv
with open('submission3_A.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['Id', 'Predicted'])
    for i, (x, y) in enumerate(sub_rnn):
        writer.writerow([i, f"{x}|{y}"])

In [81]:
import numpy as np
a=np.random.random((32,224,224,3))


In [86]:
a.shape

(32, 150528)

In [84]:
a=a.reshape(32,-1)

In [1]:
X=[
    [4,2,4],
    [4,2,4],
    [3,2,3],
    [1,3,2],
    [3,3,3],
    [3,2,1],
    [3,3,3],
    [4,1,4]
    ]

In [6]:
df=pd.DataFrame(X,columns=['h','w','p'])
df.groupby(['h','w']).count()

p
h w   
1 3  1
3 2  2
  3  2
4 1  1
  2  2

In [9]:
df.groupby(['h','w']).count().unstack()

p          
w    1    2    3
h               
1  NaN  NaN  1.0
3  NaN  2.0  2.0
4  1.0  2.0  NaN

In [15]:
df.groupby(['h','w']).count().unstack().columns

MultiIndex([('p', 1),
            ('p', 2),
            ('p', 3)],
           names=[None, 'w'])